[package]
name = "petalex"
version = "1.0.0"
authors = ["Liam Dawson <liam@liamdawson.me>"]
description = "generates and solves petal word puzzles"

[dependencies]
clap = {version = "~2.26", default-features = false}
rand = "~0.3"